language: python
python:
  - '3.5'
  - '3.6' # current default Python on Travis CI
  - '3.7'
  - '3.8'
  - '3.9'
# command to install dependencies
install:
  - pip install -r tests/requirements.txt
# command to run tests
script:
  - nosetests tests

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - main
